--Activity-1 & 2
DROP TABLE IF EXISTS MATCH;
CREATE TABLE MATCH (
    MATCH_ID INT PRIMARY KEY,
    SEASON_ID INT,
    Team1 INTEGER,
    Team2 INTEGER,
    TOSS WINNER INTEGER,
    MATCH WINNER INTEGER,
    Win_Margin INTEGER
);
INSERT INTO MATCH VALUES
(1, 2020, 1, 2, 1, 1, 10),
(2, 2020, 3, 4, 4, 3, 5),
(3, 2020, 1, 3, 3, 1, 15),
(4, 2020, 2, 4, 2, 4, 8),
(5, 2020, 1, 4, 1, 4, 12),
(6, 2020, 2, 3, 3, 2, 7),
(7, 2021, 1, 2, 2, 2, 6),
(8, 2021, 3, 4, 3, 4, 9),
(9, 2021, 1, 3, 1, 3, 11),
(10, 2021, 2, 4, 4, 2, 4);

SELECT * FROM MATCH;
SELECT COUNT(*) AS Total_Matches 
FROM MATCH;

SELECT COUNT(*) AS Mavericks_Wins
FROM MATCH
WHERE MATCH_WINNER = 1;

SELECT SEASON_ID, COUNT(*) AS Wins
FROM MATCH
WHERE MATCH_WINNER = 1
GROUP BY SEASON_ID
ORDER BY SEASON_ID;

SELECT SEASON_ID, COUNT(*) AS Total_Matches
FROM MATCH
GROUP BY SEASON_ID
ORDER BY SEASON_ID;

SELECT
    MIN(Win_Margin) AS Minimum_Win_Margin,
    MAX(Win_Margin) AS Maximum_Win_Margin,
FROM MATCH;

SELECT MATCH_ID, SEASON_ID, Win_Margin
FROM MATCH
ORDER BY Win_Margin DESC
LIMIT 3;

SELECT COUNT(*) AS TOSS AND MATCH WINNER
FROM MATCH
WHERE TOSS_WINNER = MATCH_WINNER;

SELECT 
(COUNT (*) * 100.0) / (SELECT COUNT(*) FROM MATCH) AS Win_Percentage
FROM MATCH
WHERE MATCH_WINNER = 1;

SELECT *
FROM MATCH
WHERE MATCH_WINNER IS NULL;

SELECT SEASON_ID, AVG(Win_Margin) AS Average_Win_Margin
FROM MATCH
GROUP BY SEASON_ID

SELECT MATCH_WINNER , COUNT(*) AS Wins
FROM MATCH
GROUP BY MATCH_WINNER
ORDER BY Wins DESC,
LIMIT 1;