CREATE TABLE IF NOT EXISTS STUDENT (
    ROLL_NO TEXT PRIMARY KEY,
    NAME TEXT NOT NULL,
    ADDRESS TEXT,
    PHONE TEXT
    AGE INTEGER,
);

INSERT INTO STUDENT (ROLL_NO, NAME, ADDRESS, PHONE, AGE) VALUES
('1', 'Alice', '123 Main St', '555-1234', 20),
('2', 'Bob', '456 Elm St', '555-5678', 22),
('3', 'Charlie', '789 Oak St', '555-8765', 19),
('4', 'David', '321 Pine St', '555-4321', 21),
('5', 'Eve', '654 Maple St', '555-6789', 20),
('6', 'Frank', '987 Cedar St', '555-9876', 23);

SELECT * FROM STUDENT;
SELECT * FROM STUDENT WHERE AGE = 20 AND ADDRESS = '123 Main St';
SELECT * FROM STUDENT WHERE AGE = 19 AND ADDRESS = '789 Oak St';
SELECT * FROM STUDENT WHERE AGE = 22 AND ADDRESS = '456 Elm St';
SELECT * FROM STUDENT WHERE AGE = 21 AND ADDRESS = '321 Pine St';
SELECT * FROM STUDENT WHERE AGE = 23 AND ADDRESS = '987 Cedar St';

DROP TABLE IF EXISTS PRODUCT;

DROP TABLE IF EXISTS PRODUCT;

CREATE TABLE PRODUCT (
    PRO_ID TEXT PRIMARY KEY,
    PRO_NAME TEXT NOT NULL,
    PRO_PRICE INTEGER,
    PRO_COM TEXT
);

INSERT INTO PRODUCT (PRO_ID, PRO_NAME, PRO_PRICE, PRO_COM) VALUES
('P1', 'Laptop', 1000, 'TechCorp'),
('P2', 'Smartphone', 700, 'MobileInc'),
('P3', 'Tablet', 400, 'GadgetCo'),
('P4', 'Monitor', 300, 'DisplayTech'),
('P5', 'Keyboard', 50, 'InputDevices'),
('P6', 'Mouse', 30, 'InputDevices');

SELECT * FROM PRODUCT;

SELECT PRO_NAME, PRO_PRICE 
FROM PRODUCT 
WHERE PRO_PRICE = (SELECT MIN(PRO_PRICE) FROM PRODUCT);

SELECT PRO_NAME, PRO_PRICE 
FROM PRODUCT 
WHERE PRO_PRICE = (SELECT MAX(PRO_PRICE) FROM PRODUCT);
